"""
Prompt 模块
包含所有提示词模板和常量
"""

from .prompt_template import (
    PROBLEM_DESCRIPTION_PROMPT,
    HEURISTIC_ARCHITECT_PROMPT,
    HEURISTIC_FUNCTION_CODE_GENERATION_PROMPT,
    HEURISTIC_TEMPLATE_GENERATION_PROMPT,
    HEURISTIC_CODE_INTEGRATION_PROMPT,
)

__all__ = [
    'PROBLEM_DESCRIPTION_PROMPT',
    'HEURISTIC_ARCHITECT_PROMPT',
    'HEURISTIC_FUNCTION_CODE_GENERATION_PROMPT',
    'HEURISTIC_TEMPLATE_GENERATION_PROMPT',
    'HEURISTIC_CODE_INTEGRATION_PROMPT',
]
