PROBLEM_DESCRIPTION_PROMPT = """\
Problem Background:
{problem_background}

Problem Requirement:
{problem_requirement}

Problem Formulation:
{problem_formulation}
"""

HEURISTIC_INITIALIZATION_PROMPT = '''
You are a top-tier **Algorithm Architect & Implementation Strategist**.
Your goal is to design the **architectural skeleton** AND the **concrete algorithmic logic** for a new method, `solve_with_heuristic()`, within an existing Solver Class.

### Core Philosophy: Autonomy & Rigor
1.  **Strategic Autonomy**: You have absolute freedom to select the heuristic paradigm.
2.  **Implementation Rigor**: While the strategy is open, the implementation must be precise. You must define **executable logic**, not vague intents.

### Your Workflow
1.  **Deep Analysis**: Dissect the `Problem Formulation` (Constraints, Objective) and `Existing Solver Code`.
2.  **Strategy Selection**: Decide on a specific heuristic approach.
3.  **Modular Design**: Break the strategy into atomic sub-functions (`function_architecture`).
4.  **Logic Definition**: Write detailed pseudo-code for every function.

---

## 1. Field Requirements (STRICT ENFORCEMENT)
You must adhere to these definitions to ensure the output code is compilable and logically sound.

- **name**: String. Use `_` prefix for private helpers.
- **function_descriptions**: String. **THE ALGORITHMIC CORE**.
    - **FORBIDDEN**: Vague phrases like "Calculate cost" or "Optimize result".
    - **REQUIRED**: Atomic steps with **Data Lifecycle Awareness**:
        1. **Genesis**: For ANY new `self.*` variable introduced, Step 1 MUST be "Initialize `self.variable` = ...".
        2. **Safe Access**: If accessing dynamic data, use logic like "For each item in List (if valid)...".
        3. **Math & Logic**: Explicitly mention formulas or sorting criteria (e.g., "Sort candidates by `value/weight` ratio").
        4. **Step-by-step**: "1. Loop `self.tasks`. 2. If `t.cost < limit`, add to list. 3. Return top 1."
- **inputs**: Array of objects. **(Transient Arguments Only)**.
    - **CONSTRAINT**: **DO NOT** include variables that are already class attributes (`self.*`).
    - `name`: Parameter name.
    - `type`: Python type hint.
- **outputs**: Array of objects. **(Immediate Returns Only)**.
    - **CONSTRAINT**: If the result is a state update (like "Graph Modified"), store it in `self` (Member Variable) instead of returning it.
- **member_variables_read**: Array of objects.
    - **Definition**: **Passive Data Attributes (NOUNS)**.
    - **Usage**: Reference to existing storage fields holding state (e.g., `self.graph`, `self.config_dict`).
    - **Scope**: Includes strict prerequisites required by the logic.
- **member_variables_written**: Array of objects.
    - **Definition**: **Mutations & Creations (NOUNS)**.
    - **Usage**: Reference to storage fields that are modified or created within this function.
    - **Lifecycle**: Explicitly lists any `self.*` variable that owes its **Genesis** (initial creation) to this function.
- **dependencies**: List[String].
    - **Definition**: **Executable Operations (VERBS)**.
    - **Usage**: The names of other callable member methods invoked to delegate sub-tasks.
    - **CRITICAL INTEGRITY RULE**: Every name listed here MUST satisfy one of two conditions:
        1. **It already exists** in the `Existing Solver Class Code` provided below.
        2. **It is defined as a NEW function** in your `function_architecture` output list.
    - **ORDERING HINT**: Functions listed here should ideally be defined **earlier** in the JSON list than the function calling them.

### CRITICAL GUIDELINES: DATA SCOPE STRATEGY
You must strictly distinguish between **Transient Data (Arguments)** and **Persistent State (Attributes)**.
1.  **Use Inputs/Outputs (Transient Data)** when:
    * Data is "hot potato": Generated by Step A, immediately used by Step B, and never needed again.
    * Data is a loop variable or a temporary calculation result.
2.  **Use Member Variables (Persistent State)** when:
    * Data represents a **Global State** (e.g., `self.graph`, `self.best_solution`).
    * Data must be accessed by multiple, non-adjacent functions.
    * **Initialization Rule**: If you introduce a **NEW** member variable (e.g., `self.visited_set`) that is NOT in the reference code, you **MUST** specify which function initializes it.
**RULE**: If a variable is in `member_variables_read`, it **MUST NOT** be in `inputs`. Do not pass `self.x` as an argument; access it directly inside the function.

---

## 2. Inputs
### Mathematical Modeling Problem
{problem_str}

### Existing Solver Class Code (Reference)
**Resource Rule**: You represent an extension of this class. You MUST reuse existing helper methods (pathfinding, topology checks) to ensure consistency.
Python
```
{heuristic_reference_code}
```
### Target Method Signature
Python
```
{output_function_template}
```
### Historical Insights & Experience Lessons
(Use these to avoid known pitfalls)
{experiences}

---

## 3. Output Format (CRITICAL)
Return **ONLY a valid JSON object**.
### ORDERING RULE: Bottom-Up Definition
The `function_architecture` list must be **Topologically Sorted**.
1.  **Helpers First**: Define low-level helper functions (the "callees") first.
2.  **Orchestrator Last**: The main `solve_with_heuristic` function must be the **LAST** entry in the list, as it depends on the functions above it.

### JSON Structure
JSON
```
{{
  "problem_analysis": "Brief analysis of the problem. Explain WHY you chose your specific Heuristic Strategy.",
  "strategy_overview": "A high-level summary of the algorithm's flow.",
  "function_architecture": [
    {{
      "name": "Function_Step_1",
      "strategic_role": "One-sentence summary of WHAT this function does.",
      "function_descriptions": "Step 1. Initialize self.new_var = []. Step 2. Loop through self.items. Step 3. If item meets condition X, calculate middle_val c = a/b. Step 4. Append to self.new_var. Step 5. Return nothing (optional).",
      "inputs": [
        {{
          "name": "arg_name_1",
          "type": "Type",
          "description": "..."
        }}
      ],
      "outputs": [
        {{
          "name": "arg_name_N",
          "type": "Type",
          "description": "..."
        }}
      ],
       "member_variables_read": [
        {{
          "name": "self.existing_data",
          "type": "Type",
          "description": "Used for calculation X"
        }}
      ],
      "member_variables_written": [
        {{
          "name": "self.new_var",
          "type": "List",
          "description": "Created to store valid items"
        }}
      ],
      "dependencies": ["_existing_helper_method_name"]
    }},
    ...
    {{
      "name": "solve_with_heuristic",
      "strategic_role": "Orchestrator: Main driver of the algorithm.",
      "function_descriptions": "Step 1. Call _init_state. Step 2. Call _helper_function. Step 3. Construct final self.solution. Step 4. Return self.solution.",
      "inputs": [...],
      "outputs": [
        {{"name": "solution", "type": "Any", "description": "Final solution object."}}
      ],
       "member_variables_read": [],
      "member_variables_written": [
        {{
          "name": "self.solution",
          "type": "Dict",
          "description": "Final output stored."
        }}
      ],
      "dependencies": ["Function_Step_N", "_existing_helper_method_name"]
    }}
  ]
}}
```
'''

HEURISTIC_FUNCTION_CODE_GENERATION_PROMPT = """
# Task: Implement a Heuristic Algorithm Member Function
You are an expert **Python Developer**. Your task is to implement the `{function_name}` method for a Solver Class.

**You are NOT designing the algorithm.** You are a translator converting the Architect's JSON blueprint into strict, executable Python code.

---
## 1. Existing Code Context
Use this to understand the data types of the variables.
```python
{heuristic_reference_code}
```

---

## 2. Data Flow Contract (STRICT ENFORCEMENT)
You must strictly adhere to the following IO and State permissions. **Do not deviate.**

### A. Method Signature (Arguments)
**Def**: `def {function_name}(self, {inputs_spec}):`
* **Constraint**: You MUST use exactly these argument names.
* **Constraint**: Do NOT add extra arguments (e.g., `debug=False`).

### B. Return Values
**Return**: `{outputs_spec}`
* **Constraint**: If a variable name is specified, return it. If `None`, do not return anything.

### C. State Scope (Member Variables)
You are operating within a class. You have strictly limited access to `self.*` attributes.
#### 1. READ ACCESS (Allowed `self.*` reads)
The following variables are pre-calculated and available for you to read:
{member_variables_read}
* *Usage*: Access these directly via `self.variable_name`.
#### 2. WRITE ACCESS (Allowed `self.*` mutations)
The following variables are the **only** persistent state you are allowed to modify or create:
{member_variables_written}
* *Usage*: You must update/assign these values as part of your logic.
#### 3. PROHIBITED ACTIONS (Crucial)
* **NO NEW STATE**: You are **FORBIDDEN** from creating any `self.*` variable that is not listed in "WRITE ACCESS".
* *Solution*: If you need to store temporary results (e.g., loop counters, temp dictionaries), use **local variables** (standard Python variables without `self.`).

---

## 3. The Blueprint (HIGHEST PRIORITY)
### Function Blueprint (Logic)
The Architect has defined the strict logic you must follow:
- **Strategic Role**: {function_strategic_role}
- **Implementation Steps (Pseudo-code)**:
```
{function_descriptions}
```
*Constraint*: Follow these steps strictly. Do not change the sorting keys or conditions.

### Dependencies
You must utilize these existing methods if required by the logic:
{dependencies}

---

## 4. Coding Standards (CRITICAL ENFORCEMENT)

1. **Smart "Translator" Role**: 
   - You must follow the *intent* and *steps* of the Blueprint strictly, BUT you must apply **Professional Engineering Defenses** where the pseudo-code is abstract.
   - e.g., if Logic says `if A < B`, and A is a dictionary value, you may implicitly handle `KeyError` (e.g., `val_a = data.get(A, default_value)`). **Do not crash on sparse data.**

2. **Defensive Coding Rules**:
   - **Maps/Dicts**: Never assume a key exists. Use `.get(key, default)` or `if key in dict`.
   - **Lists**: Check `if list:` before accessing `list[0]`.
   - **NoneTypes**: If a variable comes from an external source or search, check `if var is not None` before using it.
   - **Loops**: If a loop depends on a condition that might be empty, ensure it doesn't break logic.

3. **Reliability**: 
   - Do not use `raise Exception`. Return `None` or a safe fallback state if operations are impossible.
   - **Logging**: Do not use print/logging unless explicitly asked.

4. **Precision**: Translate the "Implementation Steps" line-by-line, but wrap them in the safety mechanisms described above.
---

## 5. Output Format (CRITICAL)
```python
# The code must start with `def {function_name}(self, ...):`.
```
"""

HEURISTIC_FUNCTION_CODE_FIX_PROMPT = '''
# Task: Fix a Runtime Error in Heuristic Solver
You are an expert **Python Maintenance Engineer**. Your task is to analyze a crash report (Traceback) and fix the code within the **Heuristic Solver Class**.

---

## 1. Mission
1.  **Locate**: Identify the specific function in the call stack that you are allowed to edit.
2.  **Diagnose**: Understand why the code crashed (e.g., `NoneType` access, Missing import, Invalid Method Call).
3.  **Patch**: Rewrite **ONLY** that function to fix the bug while preserving the original logic and **Return Type Integrity**.

---

## 2. Context and Inputs

### A. Full Solver Class Code (Reference)
**Context**: This code is Read-Only. Use it to check `self.*` definitions and Helper method signatures.
```python
{fullcode_snippet}
```
### B. Candidate Heuristic Functions (The "Editable Scope")
**Constraint**: You can ONLY modify functions listed here. {functions_list}
### C. Runtime Error (Traceback)
**Evidence**: Analyze this stack trace to find the root cause.
```text
{traceback_info}
```

---

## 3. Strategy: How to Fix
### Step 1: Target Selection (CRITICAL)
Iterate through the Traceback Stack Frames from the **Bottom (Most Recent Call)** to the **Top**.
- Find the **FIRST** function name that appears in your `Candidate Heuristic Functions` list.
- **Target Function**: This is the function you MUST rewrite.
- _Scenario A_: The crash happened _inside_ the Target Function. -> **Fix the logic directly.**
- _Scenario B_: The crash happened inside a Helper Method (NOT in your list) called by the Target Function. -> **Fix the Target Function (Caller)**. You must sanitize inputs _before_ calling the fragile helper.

### Step 2: Apply the Fix (The Rules)
1. **Type-Safe Fallback (CRITICAL)**:
    - **NEVER** simply return `None` if the function signature expects a specific type (e.g., `List`, `Dict`, `float`). 
    - _If expected `List`_ -> Return `[]`.
    - _If expected `float`_ -> Return `0.0` or `float('inf')`.
    - _If expected `bool`_ -> Return `False`.  
    - _Reason_: Returning `None` blindly causes `TypeError` in the _next_ step of the algorithm.   
2. **Handle `NoneType` Errors**:
    - If `AttributeError: 'NoneType' object has no attribute 'x'` occurs:
    - **Fix**: Check if the object is None _before_ accessing `.x`.
    - _Example_: `if obj is None: return fallback_value` OR `obj = obj or default_object`.
3. **Handle `KeyError` / `IndexError`**:
    - If looking up `self.graph[node]`:
    - **Fix**: Use `.get(node, default)` or check `if node in self.graph`.
4. **Handle `AttributeError` & Missing Methods (NEW)**:
    - If `AttributeError: 'int'/'str' object has no attribute 'x'` occurs:
    - **Fix**: The method does not exist on this primitive type. **DO NOT** invent methods (e.g., do not use `int.log()`).
    - **Action**: Use Python Standard Libraries (e.g., `import math` inside the function -> `math.log(x)`).

### Step 3: Coding Standards
- **Imports**: If you need standard libraries (math, random, collections, etc.) that are missing, **import them INSIDE the function**. Do not assume they are available globally.
- **No `try-except` masking**: Do not wrap the whole function in a generic `try: ... except: pass`. Fix the specific bug logic.
- **No `raise`**: Do not raise exceptions. The solver must continue running.
- **Dependencies**: You can use `self.*` variables. You are **ALLOWED** to use Python Standard Library modules (math, json, etc.) but **MUST import them locally** within the function.

---

## Output Format
Return **ONLY** the Python code for the fixed function.
- **Encapsulate in a Markdown block**: `python ...`
- **Signature**: Must match the original function exactly.
    
Python
```
def function_name(self, arg1, arg2): # Import necessary modules if missing import math
    # Fixed logic here
    ...
```
'''

HEURISTIC_REFLECT_PROMPT = """
You are a **Lead Algorithm Optimization Architect**. Your mandate is to **debug, diagnose, and rescue** a heuristic algorithm that failed to meet performance or feasibility standards.

### The Mission
  - **Analyze the Failure Type:**
    1. **TIMEOUT**: The algorithm is too slow. (Likely requires caching, incremental evaluation, or complexity reduction).
    2. **INFEASIBLE**: The solution violates constraints. (Likely requires corrected logic constraints).
  - Determine if the fix requires a **Logical Correction** (Modify existing) or a **Architectural Refactoring** (Add/Remove component).
  - **Bias towards Logical Correction** unless the architectural flaw is severe (e.g., missing caching layer, or redundant/harmful steps require removal).    

---

## 1. Architecture Field Requirements (STRICT ENFORCEMENT for MODIFY/ADD)
_Note: These requirements apply to functions being Modified or Added. Do NOT apply these to Removed functions._
- **name**: String. Use `_` prefix for private helpers.
- **function_descriptions**: String. **CRITICAL**. The detailed algorithmic logic.
    - **FORBIDDEN**: Vague statements like "Calculate the total cost of all tasks and return the result".  
    - **REQUIRED**: Atomic steps with **Data Lifecycle Awareness**:
        1. **Genesis**: For ANY new `self.*` variable introduced in this function, Step 1 MUST be "Initialize `self.variable` = ...".
        2. **Safe Access**: If accessing dynamic data, prefer logic like "For each item in List (if valid)...".
        3. **Step-by-step**: "1. Loop `self.tasks`. 2. If `t.cost < limit`, add to list. 3. Return top 1."    
- **inputs**: Array of objects. **(Transient Arguments Only)**.
    - **CONSTRAINT**: **DO NOT** include variables that are already class attributes (`self.*`).      
    - `name`: Parameter name.       
    - `type`: Python type hint.        
- **outputs**: Array of objects. **(Immediate Returns Only)**.    
    - **CONSTRAINT**: If the result is a state update (like "Graph Modified"), store it in `self` (Member Variable) instead of returning it.
- **member_variables_read**: Array of objects.
    - **Definition**: **Passive Data Attributes (NOUNS)**.
    - **Usage**: Reference to existing storage fields holding state (e.g., `self.graph`, `self.config_dict`, `self.counter`).
    - **Scope**: Includes strict prerequisites required by the logic.
- **member_variables_written**: Array of objects.
    - **Definition**: **Mutations & Creations (NOUNS)**.
    - **Usage**: Reference to storage fields that are modified or created within this function.
    - **Lifecycle**: Explicitly lists any `self.*` variable that owes its **Genesis** (initial creation) to this function.
- **dependencies**: List[String].
    - **Definition**: **Executable Operations (VERBS)**.
    - **Usage**: The names of other callable member methods invoked to delegate sub-tasks.
    - **CRITICAL INTEGRITY RULE**: Every name listed here MUST satisfy one of two conditions:
        1. **It already exists** in the `Existing Solver Class Code` provided below.
        2. **It is defined as a NEW function** in your `function_architecture` output list.
    - **PROHIBITED**: Do not list a function name here if you do not provide its definition in the JSON. The code will crash if you call an undefined function.
    - **CRITICAL INTEGRITY CHECK**: 
        1. If you list a dependency here that is NOT in the "Current Implementation", you **MUST** add a corresponding `"action": "ADD"` entry.
        2. If you **REMOVE** a function, you **MUST** check all other functions. If any function depends on the removed one, you **MUST** generate a `"action": "MODIFY"` update to remove that dependency and update its logic.

### Critical Guidelines: Data Scope Strategy (Must Read)
You must strictly distinguish between **Transient Data (Arguments)** and **Persistent State (Attributes)**.
1.  **Use Inputs/Outputs (Transient Data)** when:
    * Data is "hot potato": Generated by Step A, immediately used by Step B, and never needed again.
    * Data is a loop variable or a temporary calculation result.
2.  **Use Member Variables (Persistent State)** when:
    * Data represents a **Global State** (e.g., `self.graph`, `self.best_solution`).
    * Data must be accessed by multiple, non-adjacent functions.
    * **Initialization Rule**: If you introduce a **NEW** member variable (e.g., `self.visited_set`) that is NOT in the reference code, you **MUST** specify which function initializes it (e.g., `self.visited_set = set()`). Do not assume it exists magically.
**RULE**: If a variable is in `member_variables_read`, it **MUST NOT** be in `inputs`. Do not pass `self.x` as an argument; access it directly inside the function.

---

## 2. Inputs
### Mathematical Modeling Problem
{problem_str}
### The Failed Implementation (Code)
Python
```python
{solver_code_snippet}
```
### The Failed Architecture (Blueprint)
JSON
```json
{function_architecture}
```
### The Failure Report (Evidence)
JSON
```json
{quality_report}
```

---

## 3. Your Task: Generate Architecture Delta
Return a JSON object containing the **REDEFINED** or **NEW** function objects.
**Update Rules**:
1. **Scope**: You are allowed to **MODIFY** existing functions, **ADD** new helper functions, or **REMOVE** obsolete ones.
2. **Action Determination Protocol (STRICT)**:
    - **STEP 1**: Check if the function name exists in the "Current Architecture" list. 
    - **STEP 2**:
        - **IF EXISTS**: You **MUST** use `"action": "MODIFY"`. (Even if you are rewriting the entire logic).
        - **IF NOT EXISTS**: You may use `"action": "ADD"`.
3. **Principle of Minimalism (CRITICAL)**: Prefer **MODIFYING** existing logic in-place. Only use **ADD** if:
    - You need a new specific validator or pre-calculator to address the bottleneck.
    - The complexity of the fix requires isolation.
4. **Clean-Up Protocol (REMOVE)**: If a function becomes redundant, mark it for removal. **CRITICAL**: You **MUST** check all other functions (especially the main solver loop). If any other function calls the one you are removing, you **MUST** generate a `"action": "MODIFY"` update for that calling function to remove the dependency call.
5. **Dependency Closure**: 
    - **Add**: If Function A (Modified) calls Helper B (New), your output MUST contain entries for BOTH.
    - **Remove**: (Reinforcement) If Function A is REMOVED, you **MUST** find all functions that depend on A and **MODIFY** them to remove the dependency.

### Output Structure (JSON Only)
JSON
```
{{
  "diagnosis": "Detailed analysis of why it failed and the strategy to fix it.",
  "architecture_updates": [
    // EXAMPLE 1: Modifying an existing function
    {{
      "action": "MODIFY",
      "function_name": "existing_function_name",
      "new_definition": {{
         "name": "existing_function_name",
         "strategic_role": "...",
         "function_descriptions": "...",
         "inputs": [...], 
         "outputs": [...],
         "member_variables_read": [...],
         "member_variables_written": [...], 
         "dependencies": [...]
      }}
    }},
    // EXAMPLE 2 (OPTIONAL): Only include this block IF you created a NEW helper function
    {{
      "action": "ADD",
      "function_name": "new_helper_function",
      "new_definition": {{
         "name": "new_helper_function",
         "strategic_role": "Helper function to ...",
         "function_descriptions": "...",
         "inputs": [...], 
         "outputs": [...],
         "member_variables_read": [...],
         "member_variables_written": [...], 
         "dependencies": [...]
      }}
    }},
    // EXAMPLE 3 (OPTIONAL): Remove an obsolete function if it is no longer needed
    {{
      "action": "REMOVE",
      "function_name": "obsolete_function_name"
    }}
  ]
}}
```
"""

FEEDBACK_GUIDED_OPTIMIZATION_PROMPT = """
You are a **Lead Performance Optimization Architect**. Your goal is to **refine** a feasible but suboptimal heuristic algorithm by analyzing its execution performance data.

### The Mission
The previous algorithm works (it produces valid solutions), but the `Quality Report` indicates it is inefficient or suboptimal.
Your mandate is to **transform empirical data into algorithmic improvements**.
1.  **Analyze**: Look for patterns in the `Quality Report` (e.g., "Resource X is utilized at 99% while Y is at 10%", "Process A takes 90% of the runtime").
2.  **Hypothesize**: Determine *why* the current logic leads to these inefficiencies (e.g., "The greedy scoring function over-values factor A and ignores factor B").
3.  **Optimize**: Propose specific algorithmic adjustments.
    * *Tuning*: Adjust weights, thresholds, or sorting keys.
    * *Heuristics*: Introduce new tie-breaking rules or penalty terms based on the bottleneck data.
    * *Pruning*: Skip expensive steps that yield low ROI.

---

## 1. Architecture Field Requirements (STRICT ENFORCEMENT for MODIFY/ADD)
_Note: These requirements apply to functions being Modified or Added. Do NOT apply these to Removed functions._
- **name**: String. Use `_` prefix for private helpers.
- **function_descriptions**: String. **CRITICAL**. The detailed algorithmic logic.
    - **FORBIDDEN**: Vague statements like "Calculate the total cost of all tasks and return the result".  
    - **REQUIRED**: Atomic steps with **Data Lifecycle Awareness**:
        1. **Genesis**: For ANY new `self.*` variable introduced in this function, Step 1 MUST be "Initialize `self.variable` = ...".
        2. **Safe Access**: If accessing dynamic data, prefer logic like "For each item in List (if valid)...".
        3. **Step-by-step**: "1. Loop `self.tasks`. 2. If `t.cost < limit`, add to list. 3. Return top 1."    
- **inputs**: Array of objects. **(Transient Arguments Only)**.
    - **CONSTRAINT**: **DO NOT** include variables that are already class attributes (`self.*`).      
    - `name`: Parameter name.       
    - `type`: Python type hint.        
- **outputs**: Array of objects. **(Immediate Returns Only)**.    
    - **CONSTRAINT**: If the result is a state update (like "Graph Modified"), store it in `self` (Member Variable) instead of returning it.
- **member_variables_read**: Array of objects.
    - **Definition**: **Passive Data Attributes (NOUNS)**.
    - **Usage**: Reference to existing storage fields holding state (e.g., `self.graph`, `self.config_dict`, `self.counter`).
    - **Scope**: Includes strict prerequisites required by the logic.
- **member_variables_written**: Array of objects.
    - **Definition**: **Mutations & Creations (NOUNS)**.
    - **Usage**: Reference to storage fields that are modified or created within this function.
    - **Lifecycle**: Explicitly lists any `self.*` variable that owes its **Genesis** (initial creation) to this function.
- **dependencies**: List[String].
    - **Definition**: **Executable Operations (VERBS)**.
    - **Usage**: The names of other callable member methods invoked to delegate sub-tasks.
    - **CRITICAL INTEGRITY RULE**: Every name listed here MUST satisfy one of two conditions:
        1. **It already exists** in the `Existing Solver Class Code` provided below.
        2. **It is defined as a NEW function** in your `function_architecture` output list.
    - **PROHIBITED**: Do not list a function name here if you do not provide its definition in the JSON. The code will crash if you call an undefined function.
    - **CRITICAL INTEGRITY CHECK**: 
        1. If you list a dependency here that is NOT in the "Current Implementation", you **MUST** add a corresponding `"action": "ADD"` entry.
        2. If you **REMOVE** a function, you **MUST** check all other functions. If any function depends on the removed one, you **MUST** generate a `"action": "MODIFY"` update to remove that dependency and update its logic.

### Critical Guidelines: Data Scope Strategy (Must Read)
You must strictly distinguish between **Transient Data (Arguments)** and **Persistent State (Attributes)**.
1.  **Use Inputs/Outputs (Transient Data)** when:
    * Data is "hot potato": Generated by Step A, immediately used by Step B, and never needed again.
    * Data is a loop variable or a temporary calculation result.
2.  **Use Member Variables (Persistent State)** when:
    * Data represents a **Global State** (e.g., `self.graph`, `self.best_solution`).
    * Data must be accessed by multiple, non-adjacent functions.
    * **Initialization Rule**: If you introduce a **NEW** member variable (e.g., `self.visited_set`) that is NOT in the reference code, you **MUST** specify which function initializes it (e.g., `self.visited_set = set()`). Do not assume it exists magically.
**RULE**: If a variable is in `member_variables_read`, it **MUST NOT** be in `inputs`. Do not pass `self.x` as an argument; access it directly inside the function.

---

## 2. Inputs
### Mathematical Modeling Problem
{problem_str}
### The Failed Implementation (Code)
Python
```python
{solver_code_snippet}
```
### The Current Architecture (Blueprint)
JSON
```json
{function_architecture}
```
### The Quality Report (Performance Feedback)
CRITICAL INPUT: This report contains empirical data from the algorithm's execution. You must base your optimization strategy strictly on these findings.
JSON
```json
{quality_report}
```

---

## 3. Your Task: Generate Architecture Delta
Return a JSON object containing the **REDEFINED** or **NEW** function objects.
**Update Rules**:
1. **Scope**: You are allowed to **MODIFY** existing functions, **ADD** new helper functions, or **REMOVE** obsolete ones.
2. **Action Determination Protocol (STRICT)**:
    - **STEP 1**: Check if the function name exists in the "Current Architecture" list. 
    - **STEP 2**:
        - **IF EXISTS**: You **MUST** use `"action": "MODIFY"`. (Even if you are rewriting the entire logic).
        - **IF NOT EXISTS**: You may use `"action": "ADD"`.
3. **Principle of Minimalism (CRITICAL)**: Prefer **MODIFYING** existing logic in-place. Only use **ADD** if:
    - You need a new specific validator or pre-calculator to address the bottleneck.
    - The complexity of the fix requires isolation.
4. **Clean-Up Protocol (REMOVE)**: If a function becomes redundant, mark it for removal. **CRITICAL**: You **MUST** check all other functions (especially the main solver loop). If any other function calls the one you are removing, you **MUST** generate a `"action": "MODIFY"` update for that calling function to remove the dependency call.
5. **Dependency Closure**: 
    - **Add**: If Function A (Modified) calls Helper B (New), your output MUST contain entries for BOTH.
    - **Remove**: (Reinforcement) If Function A is REMOVED, you **MUST** find all functions that depend on A and **MODIFY** them to remove the dependency.

### Output Structure (JSON Only)

JSON
```
{{
  "diagnosis": "Detailed analysis of the Quality Report (e.g., 'The report identifies critical congestion at [Specific Location] and wasted resources at [Specific Node]. This indicates the current greedy strategy ignores [Factor X].').",
  "architecture_updates": [
    // EXAMPLE 1: Modifying an existing function
    {{
      "action": "MODIFY",
      "function_name": "existing_function_name",
      "new_definition": {{
         "name": "existing_function_name",
         "strategic_role": "...",
         "function_descriptions": "...",
         "inputs": [...], 
         "outputs": [...],
         "member_variables_read": [...],
         "member_variables_written": [...], 
         "dependencies": [...]
      }}
    }},
    // EXAMPLE 2 (OPTIONAL): Only include this block IF you created a NEW helper function
    {{
      "action": "ADD",
      "function_name": "new_helper_function",
      "new_definition": {{
         "name": "new_helper_function",
         "strategic_role": "Helper function to ...",
         "function_descriptions": "...",
         "inputs": [...], 
         "outputs": [...],
         "member_variables_read": [...],
         "member_variables_written": [...], 
         "dependencies": [...]
      }}
    }},
    // EXAMPLE 3 (OPTIONAL): Remove an obsolete function if it is no longer needed
    {{
      "action": "REMOVE",
      "function_name": "obsolete_function_name"
    }}
  ]
}}
```
"""

EXPLORATORY_REFACTORING_PROMPT = """
You are a **Visionary Algorithm Architect**. Your task is to design a **radically different** heuristic strategy to solve a complex optimization problem.

### The Mission: Paradigm Shift
The current algorithm has stagnated. To break out of the local optimum, you must design a strategy that is **structurally orthogonal** to the "Current Architecture".
1.  **Analyze the Old**: Identify the core mechanism of the `Current Architecture` (e.g., "Constructive Greedy").
2.  **Pivot**: Select a strategy from a **different algorithmic family** (e.g., if Old was Greedy, New should be Local Search, Simulated Annealing, Flow-based, or Regret-based).
3.  **Design**: Define the architectural skeleton and detailed logic for the new approach.

---
## 1. Field Requirements (STRICT ENFORCEMENT)
You must adhere to these definitions to ensure the output code is compilable and logically sound.

- **name**: String. Use `_` prefix for private helpers.
- **function_descriptions**: String. **THE ALGORITHMIC CORE**.
    - **FORBIDDEN**: Vague phrases like "Calculate cost" or "Optimize result".
    - **REQUIRED**: Atomic steps with **Data Lifecycle Awareness**:
        1. **Genesis**: For ANY new `self.*` variable introduced, Step 1 MUST be "Initialize `self.variable` = ...".
        2. **Safe Access**: If accessing dynamic data, use logic like "For each item in List (if valid)...".
        3. **Math & Logic**: Explicitly mention formulas or sorting criteria (e.g., "Sort candidates by `value/weight` ratio").
        4. **Step-by-step**: "1. Loop `self.tasks`. 2. If `t.cost < limit`, add to list. 3. Return top 1."
- **inputs**: Array of objects. **(Transient Arguments Only)**.
    - **CONSTRAINT**: **DO NOT** include variables that are already class attributes (`self.*`).
    - `name`: Parameter name.
    - `type`: Python type hint.
- **outputs**: Array of objects. **(Immediate Returns Only)**.
    - **CONSTRAINT**: If the result is a state update (like "Graph Modified"), store it in `self` (Member Variable) instead of returning it.
- **member_variables_read**: Array of objects.
    - **Definition**: **Passive Data Attributes (NOUNS)**.
    - **Usage**: Reference to existing storage fields holding state (e.g., `self.graph`, `self.config_dict`).
    - **Scope**: Includes strict prerequisites required by the logic.
- **member_variables_written**: Array of objects.
    - **Definition**: **Mutations & Creations (NOUNS)**.
    - **Usage**: Reference to storage fields that are modified or created within this function.
    - **Lifecycle**: Explicitly lists any `self.*` variable that owes its **Genesis** (initial creation) to this function.
- **dependencies**: List[String].
    - **Definition**: **Executable Operations (VERBS)**.
    - **Usage**: The names of other callable member methods invoked to delegate sub-tasks.
    - **CRITICAL INTEGRITY RULE**: Every name listed here MUST satisfy one of two conditions:
        1. **It already exists** in the `Existing Solver Class Code` provided below.
        2. **It is defined as a NEW function** in your `function_architecture` output list.
    - **ORDERING HINT**: Functions listed here should ideally be defined **earlier** in the JSON list than the function calling them.

### CRITICAL GUIDELINES: DATA SCOPE STRATEGY
You must strictly distinguish between **Transient Data (Arguments)** and **Persistent State (Attributes)**.
1.  **Use Inputs/Outputs (Transient Data)** when:
    * Data is "hot potato": Generated by Step A, immediately used by Step B, and never needed again.
    * Data is a loop variable or a temporary calculation result.
2.  **Use Member Variables (Persistent State)** when:
    * Data represents a **Global State** (e.g., `self.graph`, `self.best_solution`).
    * Data must be accessed by multiple, non-adjacent functions.
    * **Initialization Rule**: If you introduce a **NEW** member variable (e.g., `self.visited_set`) that is NOT in the reference code, you **MUST** specify which function initializes it.
**RULE**: If a variable is in `member_variables_read`, it **MUST NOT** be in `inputs`. Do not pass `self.x` as an argument; access it directly inside the function.

---

## 2. Inputs
### Mathematical Modeling Problem
{problem_str}
### Existing Solver Class Code (Reference)
**Resource Rule**: Check existing helper methods (e.g., pathfinding, topology checks) in the code above. **You MUST reuse them** in your logic instead of reinventing them.
Python
```
{heuristic_reference_code}
```
### Target Method Signature
Python
```
{output_function_template}
```
### Historical Insights & Experience Lessons
(Use these to avoid known pitfalls)
{experiences}

### The Current (Stagnant) Architecture
**CONSTRAINT**: Do NOT replicate this logic. Use it only as a reference of what **NOT** to do.
JSON
```json
{function_architecture}
```

---

## 3. Output Format (CRITICAL)
Return **ONLY a valid JSON object**.
### ORDERING RULE: Bottom-Up Definition
The `function_architecture` list must be **Topologically Sorted**.
1.  **Helpers First**: Define low-level helper functions (the "callees") first.
2.  **Orchestrator Last**: The main `solve_with_heuristic` function must be the **LAST** entry in the list, as it depends on the functions above it.

### JSON Structure
JSON
```
{{
  "problem_analysis": "Brief analysis of the problem. Explain WHY you chose your specific Heuristic Strategy.",
  "strategy_overview": "A high-level summary of the algorithm's flow.",
  "function_architecture": [
    {{
      "name": "Function_Step_1",
      "strategic_role": "One-sentence summary of WHAT this function does.",
      "function_descriptions": "Step 1. Initialize self.new_var = []. Step 2. Loop through self.items. Step 3. If item meets condition X, calculate middle_val c = a/b. Step 4. Append to self.new_var. Step 5. Return nothing (optional).",
      "inputs": [
        {{
          "name": "arg_name_1",
          "type": "Type",
          "description": "..."
        }}
      ],
      "outputs": [
        {{
          "name": "arg_name_N",
          "type": "Type",
          "description": "..."
        }}
      ],
       "member_variables_read": [
        {{
          "name": "self.existing_data",
          "type": "Type",
          "description": "Used for calculation X"
        }}
      ],
      "member_variables_written": [
        {{
          "name": "self.new_var",
          "type": "List",
          "description": "Created to store valid items"
        }}
      ],
      "dependencies": ["_existing_helper_method_name"]
    }},
    ...
    {{
      "name": "solve_with_heuristic",
      "strategic_role": "Orchestrator: Main driver of the algorithm.",
      "function_descriptions": "Step 1. Call _init_state. Step 2. Call _helper_function. Step 3. Construct final self.solution. Step 4. Return self.solution.",
      "inputs": [...],
      "outputs": [
        {{"name": "solution", "type": "Any", "description": "Final solution object."}}
      ],
       "member_variables_read": [],
      "member_variables_written": [
        {{
          "name": "self.solution",
          "type": "Dict",
          "description": "Final output stored."
        }}
      ],
      "dependencies": ["Function_Step_N", "_existing_helper_method_name"]
    }}
  ]
}}
```
"""